FROM python:3.11-slim-buster
WORKDIR /app
COPY ./app/requirements.txt /app/requirements.txt

RUN pip install --upgrade pip
RUN pip install huggingface_hub==0.23.1
RUN pip install -r /app/requirements.txt
COPY ./app/ /app
COPY ./run.py /

ENTRYPOINT [ "python" ]
CMD ["run.py"]